### ISSUE TITLE
3 direccions sprite error

### ISSUE THREAD

**Issue by albertllopart** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#10]
Quan camines amb dues direccions (diagonal) contra una de les següents cantonades (dalt esquerra, dalt dreta, baix esquerra) L'sprite del Link rebota entre dues direccions.

**Comment by Jordior97** [comment]
Solved, in Movement() state of the player, now we detect if you can't move, and we aplly only the last direction the player was moving
