### ISSUE TITLE
game Randomly crashed!

### ISSUE THREAD

**Issue by albertllopart** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#13]
Després d'estar uns 5 minuts per fora de casa destruïnt-ho tot el joc m'ha crashejat just al tornar a entrar. No he pogut recrear-ho.

**Comment by albertllopart** [comment]
Crec que té a veure amb colliders.

**Comment by Jordior97** [comment]
Solved (problem with colliders deletion)
