### ISSUE TITLE
Camera displacement

### ISSUE THREAD

**Issue by mickadoos** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#25]
Quan un soldier t'ataca i et fa retrocedir contra una pared, et posa sobre la pared i et desplaça lleugerament la càmara. 

Steps:
1. Surt de la casa.
2. Dirigeix-te a l'esquerra
3. Trenca 2 bushes amb sword
4. Puja fins trobar-te el soldat que està darrere la casa
5. Et situes prop de cantonada entre la pared i el soldat
6. T'esperes a que el soldat s'acosti i t'ataca i faci retrocedir

Quan la distància de retrocés de l'atac, es més gran que la distància que deixes entre la pared i el Link, es produeix un petit desplaçament de la càmara. La càmara es restableix quan camines a la direcció contrària.

**Comment by elliotjb** [comment]
Fixed
