### ISSUE TITLE
superposicion de sprites

### ISSUE THREAD

**Issue by SrPerso** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#39]
**build: ** 0.7
**priority:** medium
**description:** the objects that link carry is supperpossed to the others

image:
![captura](https://cloud.githubusercontent.com/assets/17146733/25797122/43c3fb2c-33dc-11e7-90ec-99e4a7b3dbf6.PNG)

**Comment by xDragan** [comment]
fixed
