### ISSUE TITLE
Crash when killing a Geodude

### ISSUE THREAD

**Issue by albertllopart** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#49]
**CATEGORY:**
[ ]Rattata    
[ ]Charmeleon    
[x ]Dragonite    

**PRIORITY:**
[x ]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**DESCRIPTION:**
Random crash after killing a Geodude

**STEPS TO REPRODUCE:**
Entering victory road via normal gameplay and killing the first geodude.

**FREQUENCY:**
once

**OTHER INFO / SS / GIF:**

**Comment by xDragan** [comment]
fixed
