### ISSUE TITLE
Map disappear very few times

### ISSUE THREAD

**Issue by Sergio111** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#50]
**CATEGORY:**
[ ]Rattata    
[X ]Charmeleon    
[ ]Dragonite    

**PRIORITY:**
[X ]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**DESCRIPTION:**
Map disappears sometimes

**STEPS TO REPRODUCE:**
Open the game, when you are in Link house use Alt + Tab. Sometimes the map disappears and only Link and the UI stays.

**FREQUENCY:**
1/20.

**OTHER INFO / SS / GIF:**

**Comment by xDragan** [comment]
fixed
