### ISSUE TITLE
Arrow colliders some time don't work

### ISSUE THREAD

**Issue by Sergio111** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#51]
**CATEGORY:**
[ ]Rattata    
[X ]Charmeleon    
[ ]Dragonite    

**PRIORITY:**
[X ]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**DESCRIPTION:**

Sometimes the arrows doesn't hit and you can't grab them.

**STEPS TO REPRODUCE:**

Play the game and shot arrows

**FREQUENCY:**

1/10.

**OTHER INFO / SS / GIF:**

**Comment by elliotjb** [comment]
Fixed
