### ISSUE TITLE
When you go out of the miniboss room you can't enter again (maybe colliders)

### ISSUE THREAD

**Issue by Sergio111** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#52]
**CATEGORY:**
[ ]Rattata    
[X]Charmeleon    
[ ]Dragonite    

**PRIORITY:**
[X]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**DESCRIPTION:**
Sometimes when you enter the miniboss room and then you go out you can't enter again.

**STEPS TO REPRODUCE:**
Enter miniboss room, fight with him sometime, the go out and try to enter again.

**FREQUENCY:**
1/12

**OTHER INFO / SS / GIF:**

**Comment by elliotjb** [comment]
Fixed
