### ISSUE TITLE
When you kill a soldier the game crashes (maybe colliders)

### ISSUE THREAD

**Issue by Sergio111** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#53]
**CATEGORY:**
[ ]Rattata    
[ ]Charmeleon    
[X ]Dragonite    

**PRIORITY:**
[X ]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**DESCRIPTION:**

Sometimes when you kill a soldier the game crashes.

**STEPS TO REPRODUCE:**

Play the game and kill some soldiers.

**FREQUENCY:**

2/10

**OTHER INFO / SS / GIF:**

**Comment by xDragan** [comment]
fixed
