### ISSUE TITLE
When you kill a Ganon minion the game crashes (colliders almost sure)

### ISSUE THREAD

**Issue by Sergio111** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#54]
**CATEGORY:**
[ ]Rattata    
[ ]Charmeleon    
[X]Dragonite    

**PRIORITY:**
[X]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**DESCRIPTION:**

Sometimes when you kill some miniboss minions the game crashes.

**STEPS TO REPRODUCE:**

Go to the boss room and kill some miniboss minions in the second phase.

**FREQUENCY:**

1/5

**OTHER INFO / SS / GIF:**

**Comment by xDragan** [comment]
fixed
