### ISSUE TITLE
Ganon and his minion sprites do extrange things when they move

### ISSUE THREAD

**Issue by Sergio111** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#55]
**CATEGORY:**
[X]Rattata    
[ ]Charmeleon    
[ ]Dragonite    

**PRIORITY:**
[ ]Urgent  
[ ]High  
[X]Normal  
[ ]Low  

**DESCRIPTION:**

When you fight with Ganon if it moves to the sides it's extrange and the miniboss minions do extrange things in diagonal.

**STEPS TO REPRODUCE:**

Fight with the boss.

**FREQUENCY:**

**OTHER INFO / SS / GIF:**

**Comment by xDragan** [comment]
fixed
