### ISSUE TITLE
When you kill the miniboss the game crashes (colliders maybe)

### ISSUE THREAD

**Issue by Sergio111** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#56]
**CATEGORY:**
[ ]Rattata    
[ ]Charmeleon    
[X]Dragonite    

**PRIORITY:**
[X]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**DESCRIPTION:**

When you kill the miniboss the game crashes.

**STEPS TO REPRODUCE:**

Play the game fight the miniboss and kill it.

**FREQUENCY:**

1/10

**OTHER INFO / SS / GIF:**

**Comment by xDragan** [comment]
fixed
