### ISSUE TITLE
Extrange grab objects bug

### ISSUE THREAD

**Issue by Sergio111** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#57]
**CATEGORY:**
[ ]Rattata    
[X]Charmeleon    
[ ]Dragonite    

**PRIORITY:**
[ ]Urgent  
[ ]High  
[ ]Normal  
[X]Low  

**DESCRIPTION:**

Sometimes if you grab an object and change te map with the object you can't move the player anymore.

**STEPS TO REPRODUCE:**

Start the game grab a pot and go out of the house without throwing it. Then enter to the house another time, try to grab a new one and the bug may appear.

**FREQUENCY:**

1/5

**OTHER INFO / SS / GIF:**

**Comment by xDragan** [comment]
fixed
