### ISSUE TITLE
Moving while item menu opened.

### ISSUE THREAD

**Issue by mickadoos** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#58]
**CATEGORY:**
[X]Rattata    
[ ]Charmeleon    
[ ]Dragonite    

**PRIORITY:**
[ ]Urgent  
[ ]High  
[ ]Normal  
[X]Low  

**DESCRIPTION:**
Can move while item menu is open. (Zelda World, Link's House)

**STEPS TO REPRODUCE:**
1. Get outside Link's House
2. Press "A" next to the post.
3. While text is open -> Press "start" and open the menu item.
4. Press "A" again. The text will close and you can move with item menu opened.

**FREQUENCY:**
Always.

**OTHER INFO / SS / GIF:**

**Comment by elliotjb** [comment]
Fixed
