### ISSUE TITLE
Bow equiped, but shooting hook

### ISSUE THREAD

**Issue by mickadoos** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#60]
**CATEGORY:**
[ ]Rattata    
[X]Charmeleon    
[ ]Dragonite    

**PRIORITY:**
[ ]Urgent  
[ ]High  
[X]Normal  
[ ]Low  

**DESCRIPTION:**
After shooting hook, if you open the item menu and switch to another item, then this item equipped will function like the hook.

**STEPS TO REPRODUCE:**
1. Get the item "hook".
2. Open the item menu "start".
3. Select and equip "B" the hook.
4. Charge the bar by holding "B".
5. After shooting the hook press "start", and open the menu.
6. Switch to another item and equip "B".
7. Close the menu and charge the bar by holding "B".
(You will see that the other item: bow or bombs, has the function like the hook)

**FREQUENCY:**
Always.

**OTHER INFO / SS / GIF:**

**Comment by xDragan** [comment]
fixed
