### ISSUE TITLE
You can move with the Pokemon menu opened (MODIFIED: NOT ONLY ON POKEMON WORLD)

### ISSUE THREAD

**Issue by mickadoos** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#62]
**CATEGORY:**
[X]Rattata    
[ ]Charmeleon    
[ ]Dragonite    

**PRIORITY:**
[ ]Urgent  
[ ]High  
[ ]Normal  
[X]Low  

**DESCRIPTION:**
You can move with the Pokemon menu opened (Pokemon world, Victory Road).

MODIFIED: NOT ONLY ON POKEMON WORLD, it happens with item menu of Zelda too.
It occurs always when you pass a 'door' to another zone.

**STEPS TO REPRODUCE:**
1. Just after you go outside of the cave of Vitcory Road, press "start" fast and open Pokemon menu.
2. Wait a short time pressing "D-pad" and try to move.
(You can move while the Pokemon menu is opened)

**FREQUENCY:**
Always, but, this only occurs when you pass a door to another zone. Quickly after passing to the another zone if you open press "start" then it occurs.

**OTHER INFO / SS / GIF:**

**Comment by xDragan** [comment]
temprarly fixed, wip
