### ISSUE TITLE
BREAK! Salamance combat

### ISSUE THREAD

**Issue by mickadoos** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#65]
**CATEGORY:**
[ ]Rattata    
[ ]Charmeleon    
[X]Dragonite    

**PRIORITY:**
[X]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**DESCRIPTION:**
When Salamance and Swampert abilities collision meet. The game breaks.

-> "Swampert.cpp" line 173

**STEPS TO REPRODUCE:**

**FREQUENCY:**

**OTHER INFO / SS / GIF:**

**Comment by elliotjb** [comment]
Fixed
