### ISSUE TITLE
BREAK! Talking with Phoebe

### ISSUE THREAD

**Issue by mickadoos** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#66]
**CATEGORY:**
[ ]Rattata    
[ ]Charmeleon    
[X]Dragonite    

**PRIORITY:**
[X ]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**DESCRIPTION:**
Interacting with Phoebe, before the text ends it breaks.

**STEPS TO REPRODUCE:**
Talking to Phoebe.

**FREQUENCY:**
Rarely.

**OTHER INFO / SS / GIF:**

**Comment by xDragan** [comment]
fixed
