### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by xDragan** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#7]
Entering and going out of the house crashes the game sometimes (10%)
http://prntscr.com/ejstpo

How to replicate: enter the house 10 times in arrow aprox.

**Comment by elliotjb** [comment]
Fixed bug. Look [Commit Fix this bug](https://github.com/NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE/commit/713bf7a8a2a1b8069342675a2d7c53bff52f7983)
