### ISSUE TITLE
Camera follow bug

### ISSUE THREAD

**Issue by xDragan** [NontendoSL/Zelda-a-Link-to-the-Past-TRIBUTE#8]
If we go to the part of the left soldiers, we can block link and the camera will go out of the map.

GIF here: https://gyazo.com/4ebe1d82ef07f47c8e3277810d1b1726

Probably fixing just Hitboxes a bit

**Comment by Jordior97** [comment]
Solved, now the camera follows Link position, only wen it is changing (not movement)
